// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountrySelect: typeof import('./components/CountrySelect.vue')['default']
    FilterCard: typeof import('./components/FilterCard.vue')['default']
    FilterForm: typeof import('./components/FilterForm.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    Route: typeof import('./components/Route.vue')['default']
    RoutesPull: typeof import('./components/RoutesPull.vue')['default']
  }
}

export { }
